# Generated by Django 2.2.8 on 2019-12-14 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='searchword',
            options={'verbose_name': 'Сохраненные параметры поиска', 'verbose_name_plural': 'Сохраненные параметры поиска'},
        ),
        migrations.AddField(
            model_name='lot',
            name='has_request',
            field=models.BooleanField(default=False, verbose_name='Наличие заявок'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Area', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='url',
            field=models.URLField(max_length=150, unique=True, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Список товаров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='aggregator.Category')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Список товаров',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='aggregator.Region'),
        ),
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='lot',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='aggregator.SubCategory', verbose_name='Список товаров'),
        ),
    ]
