# Generated by Django 2.2.8 on 2019-12-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20191214_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('type', models.CharField(choices=[('authentication', 'Авторизация'), ('change_phone', 'Смена телефона')], default='authentication', max_length=255)),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=20, verbose_name='Код подтверждения')),
                ('is_used', models.BooleanField(default=False, verbose_name='Был использован?')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_aggregator_confirmationcodes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'db_table': 'authentication_confirmation_codes',
                'get_latest_by': 'id',
            },
        ),
    ]
